apps/tinymce/urls.py
# Copyright (c) 2008 Joost Cassee
# Licensed under the terms of the MIT License (see LICENSE.txt)

from django.conf.urls.defaults import *

urlpatterns = patterns('tinymce.views',
    url(r'^js/textareas/(?P<name>.+)/$', 'textareas_js', name='tinymce-js'),
    url(r'^js/textareas/(?P<name>.+)/(?P<lang>.*)$', 'textareas_js', name='tinymce-js-lang'),
    url(r'^spellchecker/$', 'spell_check'),
    url(r'^flatpages_link_list/$', 'flatpages_link_list'),
    url(r'^compressor/$', 'compressor', name='tinymce-compressor'),
    url(r'^filebrowser/$', 'filebrowser', name='tinymce-filebrowser'),
    url(r'^preview/(?P<name>.+)/$', 'preview', name='tinymce-preview'),
)

django/conf/project_template/urls.py
from django.conf.urls.defaults import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', '{{ project_name }}.views.home', name='home'),
    # url(r'^{{ project_name }}/', include('{{ project_name }}.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

urls.py
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template
from django.views.generic import list_detail

handler500 = 'djangotoolbox.errorviews.server_error'

# Django Admin
from django.contrib import admin
admin.autodiscover()

# Search for "dbindexes.py" in all installed apps
import dbindexer
dbindexer.autodiscover()

# Search for "search_indexes.py" in all installed apps
import search
search.autodiscover()

from accounts.forms import UserProfileForm
from jobs.models import Entry, Category, Company

from jobs.feeds import LatestJobsFeed, LatestCompaniesFeed
from jobs.sitemap import EntrySitemap, CategorySitemap, CompanySitemap

feeds = {
    'jobs': LatestJobsFeed,
    'companies': LatestCompaniesFeed,
}

sitemaps = {
    'jobs': EntrySitemap,
    'categories': CategorySitemap,
    'companies': CompanySitemap,
}


urlpatterns = patterns('',

    url(r'^$', 'views.home_page', name='home_page',),
    url(r'^about/$', direct_to_template,{ 'template':'about.html',}, name='about_page',),
    url(r'^about/faq/$', direct_to_template,{ 'template':'faq.html',}, name='faq_page',),

    # Jobs
    (r'^v/', include('jobs.urls')),

    # Blog 
    (r'^b/', include('posts.urls')),

    # Accounts
    # url(r'accounts/', include('social_auth.urls')),
    # url(r'accounts/logout/$', 'views.logout_page', name='logout_page'),

    # Warmup
    ('^_ah/warmup$', 'djangoappengine.views.warmup'),

    # Django Admin
    (r'^admin/', include(admin.site.urls)),

    # TinyMCE
    (r'^tinymce/', include('tinymce.urls')),

    # Profiles
    url(r'^profile-redirect/$', 'views.profile_redirect', name='profile_redirect'),
    (r'^p/create/', 'profiles.views.create_profile', {'form_class': UserProfileForm,}),
    (r'^p/(?P<username>\w+)/$', 'profiles.views.profile_detail',
        {
            'extra_context': {
                              'object_list':Entry.objects.all(),
                              'company_list':Company.objects.all(),
                              },
        }),
    (r'^p/edit', 'profiles.views.edit_profile',
        {
        'form_class': UserProfileForm,
        'success_url':'/profile-redirect/',
        }),
    (r'^p/', include('profiles.urls'),),

    # Feeds
    (r'^feed/(?P<url>.*)/$', 'django.contrib.syndication.views.feed',
        {'feed_dict': feeds}, ),

    # SiteMap
    url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.index',
        {'sitemaps': sitemaps}, name='sitemap'),
    url(r'^sitemap-(?P<section>.+)\.xml$', 'django.contrib.sitemaps.views.sitemap',
        {'sitemaps': sitemaps},),

)

apps/jobs/models.py
import datetime

from django.conf import settings
from django.contrib.auth.models import User
from django.db import models

from django.utils.translation import ugettext_lazy as _
from django.template.defaultfilters import slugify

from accounts.models import UserProfile

class Company(models.Model):
    name = models.CharField(max_length=100, help_text=_('Maximum 100 characters.'))
    slug = models.SlugField(help_text=_("Suggested value automatically generated from title. Must be unique."))
    pub_date = models.DateTimeField(default=datetime.datetime.now)
    address = models.CharField(max_length=250, help_text=_('Company location or address. Maximum 100 characters.'))
    telephone = models.CharField(max_length=50, help_text=_('Company telephone or landline number. Maximum 50 characters.'))
    fax = models.CharField(max_length=50, blank=True, help_text=_('Company facsimile/fax number. Maximum 50 characters.'))
    email = models.EmailField(max_length=50, help_text=_('Company email address. Maximum 50 characters.'))
    url = models.URLField(max_length=250, blank=True, help_text=_('Company website url. Maximum 250 characters.'))
    description_html = models.TextField(help_text=_("An overview or a short description of your company.") )
    author = models.ForeignKey(User)

    class Meta:
        ordering = ['name']
        verbose_name_plural = _("Companies")

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return ('job_company_detail', (), {'object_id':self.id, 'slug':self.slug})

    get_absolute_url = models.permalink(get_absolute_url)

    def save(self, force_insert=False, force_update=False):
        self.slug = slugify(self.name)
        super(Company, self).save(force_insert, force_update)

#    def live_entry_set(self):
#        from jobs.models import Entry
#        return self.entry_set.filter(company=Entry.company)


class Category(models.Model):
    title = models.CharField(max_length=250,
        help_text=_('Maximum 50 characters.'))
    slug = models.SlugField(unique=True,
        help_text=_("Suggested value automatically generated from title. Must be unique."))
    pub_date = models.DateTimeField(default=datetime.datetime.now)
    description_html = models.TextField(help_text=_("Short description"), blank=True)

    class Meta:
        ordering = ['title']
        verbose_name_plural = _("Categories")

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return ('job_category_detail', (), {'slug':self.slug})

    get_absolute_url = models.permalink(get_absolute_url)

    def live_entry_set(self):
        from jobs.models import Entry
        return self.entry_set.filter(status=Entry.LIVE_STATUS)


class LiveEntryManager(models.Manager):
    def get_query_set(self):
        return super(LiveEntryManager, self).get_query_set().filter(status=self.model.LIVE_STATUS)

class ExpiredEntryManager(models.Manager):
    def get_query_set(self):
        return super(ExpiredEntryManager, self).get_query_set().filter(status=self.model.EXPIRED_STATUS)

class DraftsEntryManager(models.Manager):
    def get_query_set(self):
        return super(DraftsEntryManager, self).get_query_set().filter(status=self.model.DRAFT_STATUS)


class Entry(models.Model):

    LIVE_STATUS = 1
    DRAFT_STATUS = 2
    EXPIRED_STATUS = 3
    HIDDEN_STATUS = 4
    STATUS_CHOICES = (
        (LIVE_STATUS, 'Live'),
        (DRAFT_STATUS, 'Draft'),
        (EXPIRED_STATUS, 'Expired'),
        (HIDDEN_STATUS, 'Hidden'),
    )

    TWO_MONTHS = 1
    FOUR_MONTHS = 2
    SIX_MONTHS = 3
    VISIBILITY_CHOICES = (
        (TWO_MONTHS, 'Two Months'),
        (FOUR_MONTHS, 'Four Months'),
        (SIX_MONTHS, 'Six Months'),
    )

    FULL_TIME = 1
    PART_TIME = 2
    JOB_TYPE_CHOICES = (
        (FULL_TIME, 'Full Time'),
        (PART_TIME, 'Part Time'),
    )

    LOCATION_CHOICES = (
        ('Home', (
                ('Home','Work from home'),
            )
        ),
        ('Philippines', (
                ('ARMM','Armm'),
                ('BICOL_REGION','Bicol Region'),
                ('CAR','C.A.R.'),
                ('CAGAYAN_VALLEY','Cagayan Valley'),
                ('CARAGA','Caraga'),
                ('CENTRAL_LUZON','Central Luzon'),
                ('CENTRAL_MINDANAO','Central Mindanao'),
                ('CENTRAL_VISAYAS','Central Visayas'),
                ('EASTERN_VISAYAS','Eastern Visayas'),
                ('ILOCOS_REGION','Ilocos Region'),
                ('NCR','National Capital Region'),
                ('NORTHERN_MINDANAO','Northern Mindanao'),
                ('SOUTHERN_MINDANAO','Southern Mindanao'),
                ('SOUTHERN_TAGALOG','Southern Tagalog'),
                ('WESTERN_MINDANAO','Western Mindanao'),
                ('WESTERN_VISAYAS','Western Visayas'),
            )
        ),
        ('Overseas', (
                ('BANGLADESH', 'Bangladesh'),
                ('CHINA', 'China'),
                ('HONG_KONG', 'Hong Kong'),
                ('INDIA', 'India'),
                ('INDONESIA', 'Indonesia'),
                ('JAPAN', 'Japan'),
                ('MALAYSIA', 'Malaysia'),
                ('SINGAPORE', 'Singapore'),
                ('THAILAND', 'Thailand'),
                ('VIETNAM', 'Vietnam'),
            )
        ),
        ('Other', (
                ('AFRICA', 'Africa'),
                ('ASIA_MIDDLE_EAST', 'Asia - Middle East'),
                ('ASIA_OTHERS', 'Asis - Others'),
                ('AUSTRALIA', 'Australia'),
                ('NEW_ZEALAND', 'New Zealand'),
                ('EUROPE', 'Europe'),
                ('NORTH_AMERICA', 'North America'),
                ('SOUTH_AMERICA', 'South America'),
            )
        ),
    )


    # Core fields.
    job_title = models.CharField(max_length=100, help_text=_("Maximum 100 characters."))
    slug = models.SlugField(max_length=100, help_text=_("Suggested value automatically generated from title."))
    body_html = models.TextField(help_text=_("Include here the job overview, description, qualifications..etc"))
    howto_apply_html = models.TextField(help_text=_("Instructions on how to apply.."))
    salary = models.CharField(max_length=100, blank=True, help_text=_("Salary, if confidential leave blank.") )
    location = models.CharField(max_length=20, choices=LOCATION_CHOICES, default=LOCATION_CHOICES[0],
        help_text=_("By default we reserve the right to review the job posting before it is publicly displayed."))

    # Metadata.
    author = models.ForeignKey(User)
    has_expired = models.BooleanField(default=False)
    status = models.IntegerField(choices=STATUS_CHOICES, default=DRAFT_STATUS,
        help_text=_("By default we reserve the right to review the job posting before it it publicly displayed."))
#    type = models.IntegerField(choices=JOB_TYPE_CHOICES, default=FULL_TIME,
#        help_text=_("Specify job type."))
    visibility = models.IntegerField(choices=VISIBILITY_CHOICES, default=TWO_MONTHS,
        help_text=_("Specify how long the job will be available."))
    pub_date = models.DateTimeField(default=datetime.datetime.now)

    # Categorization. Industry/Specialization
    categories = models.ForeignKey(Category)
    company_name = models.ForeignKey(Company)

    objects = models.Manager()
    live = LiveEntryManager()
    expired = ExpiredEntryManager()
    drafts = DraftsEntryManager()

    class Meta:
        ordering = ['-pub_date']
        verbose_name_plural = _("Job Entries")

    def __unicode__(self):
        return self.job_title

    def save(self, force_insert=False, force_update=False):
        self.slug = slugify(self.job_title)
        super(Entry, self).save(force_insert, force_update)

    def get_absolute_url(self):
        return ('job_entry_detail', (), { 'slug': self.slug, 'object_id':self.id,  })

    get_absolute_url = models.permalink(get_absolute_url)

templates/about.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "About" %}{% endblock%}

{% block content %}
<p>Greetings! Welcome to <strong>Python Jobs PH</strong> where you can post free Jobs for Python developers. 
The site's primary focus is to promote Python programming related jobs in the Philippines.</p>
<p>You can also join the community at <a href="http://groups.google.com/group/pinoy-python-users" target="_blank">Pinoy Python Users Group</a></p>
<p>For feedback/questions you can reach me at:<br />python -c "print ''.join(['rbbeltran','.','09','@','gmail','.','com'])"</p>
{% endblock %}

{% block meta %}
<meta name="description" content="{{settings.SITE_DESCRIPTION}}" />
<meta name="keywords" content="{{settings.SITE_KEYWORDS|join:', '}}" />
{% endblock%}

templates/base.html
<!DOCTYPE html> {% load i18n %}
<html dir="{% if LANGUAGE_BIDI %}rtl{% else %}ltr{% endif %}" lang="{% firstof LANGUAGE_CODE 'en' %}">
<head>
<meta charset="UTF-8" />
<title>{%block title%}{%endblock%} | {% trans settings.SITE_NAME %}</title>
<link rel="profile" href="http://gmpg.org/xfn/11" />
<link rel="stylesheet" type="text/css" href="{{prefix_abs_uri}}{{settings.MEDIA_URL}}css/style.css" />
<link rel="alternate" type="application/rss+xml" title="{% trans settings.SITE_NAME %} Feed" href="{{prefix_abs_uri}}/feed/jobs/" />
<link rel="alternate" type="application/rss+xml" title="{% trans settings.SITE_NAME %} Feed" href="{{prefix_abs_uri}}/feed/companies/" />
<link rel="index" title="{% trans settings.SITE_NAME %}" href="{{prefix_abs_uri}}/" />
{% block meta %}{% endblock%}
{% if not settings.DEBUG %}
  {% load analytics %}
  {% ga %}
{% endif %}
<!-- <script type="text/javascript" src="{{settings.MEDIA_URL}}js/jquery.min.js"></script> -->
<script type="text/javascript" src="{{prefix_abs_uri}}{{settings.MEDIA_URL}}js/tiny_mce/tiny_mce.js"></script> 
<script type="text/javascript">
tinyMCE.init({
        mode : "textareas",
        theme : "advanced",
        theme_advanced_buttons1 : "bold,italic,underline,strikethrough,bullist,numlist,justifyleft,justifycenter,justifyright,justifyfull,removeformat,code",
        theme_advanced_buttons2 : "",
        theme_advanced_buttons3 : "",
        theme_advanced_buttons4 : "",
        theme_advanced_toolbar_align : "center",
});
</script>

  <style type="text/css">
  table.formset tr td {
    width: 90%;
  }
  #id_name,
  #id_address, #id_telephone,
  #id_fax, #id_email, #id_url {
    width: 100%;
  }
  #id_description_html {
    width: 100%;
    height: 500px;
  }
  .helptext {
  font-size: smaller;
  color: green;
  }
  ul.errorlist {
  color: red;
  font-size: smaller;
  }
  #id_job_title, #id_salary {
    width: 100%;
  }
  #id_body_html {
    width: 100%;
    height: 400px;
  }
  #id_howto_apply_html {
    width: 100%;
    height: 200px;
  }
  </style>
{% block extrastyle %}{% endblock%}
</head>
<body class="home blog" onload="prettyPrint();">
<div id="wrapper" class="hfeed">
<div id="header">
<div id="masthead">
<div id="branding" role="banner">
  <h1 id="site-title">
    <span> 
      <a href="{{prefix_abs_uri}}/" title="{% trans settings.SITE_NAME %} " rel="home">{% trans settings.SITE_NAME %} </a>
    </span>
  </h1>
  <div id="site-description">{% trans settings.SITE_DESCRIPTION %}</div>
</div><!-- #branding -->
<div id="access" role="navigation">
  <div class="skip-link screen-reader-text"><a href="#content" title="{% trans 'Skip to content' %}">{% trans "Skip to content" %}</a></div>
    <div class="menu">
      <ul>
        <li class="page_item current_page_item"><a href="{{prefix_abs_uri}}/" title="{% trans 'Home' %}">{% trans "Home" %}</a></li>
        <li class="page_item current_page_item"><a href="{{prefix_abs_uri}}{% url about_page %}" title="{% trans 'About' %}">{% trans "About"%} </a></li>
        <li class="page_item current_page_item"><a href="{{prefix_abs_uri}}{% url faq_page %}" title="{% trans 'Faq' %}">{% trans "Faq"%} </a></li> 
        <li class="page_item current_page_item"><a href="{{prefix_abs_uri}}{% url job_company_list %}" title="{% trans 'View companies' %}">Companies</a></li> 
{% if user.is_authenticated %}
        <li class="page_item current_page_item"><a href="{{prefix_abs_uri}}{% url post_job %}" title="{% trans 'Add a new Job' %}">{% trans "New Job"%} </a></li> 
        <li class="page_item current_page_item"><a href="{{prefix_abs_uri}}{% url post_company %}" title="{% trans 'Add a new company' %}">{% trans "New Company"%} </a></li> 
        <li class="page_item current_page_item"><a href="{{prefix_abs_uri}}{% url logout_page %}" title="{% trans 'Logout' %}">{% trans "Logout"%} </a></li> 
        <li class="page_item current_page_item"><a href="{{prefix_abs_uri}}{% url profiles_profile_detail user.username %}" title="{% trans 'View profile.' %}">{{user.username}}</a></li> 
{% else %}
        <li class="page_item current_page_item"><a href="#" title="{% trans 'Gmail Login' %}">{% trans "Login"%} </a></li> 
        {% comment %} <li class="page_item current_page_item"><a href="{{prefix_abs_uri}}{% url begin backend='google' %}" title="{% trans 'Gmail Login' %}">{% trans "Login"%} </a></li> {% endcomment %}
{% endif %}
        <li class="page_item current_page_item"><a href="{{prefix_abs_uri}}{% url profiles_profile_list %}" title="{% trans 'User profiles' %}">Profiles</a></li> 
        <li class="page_item current_page_item"><a href="{{prefix_abs_uri}}{% url post_list %}" title="{% trans 'Blog' %}">Blog</a></li> 
      </ul>
    </div>
</div><!-- #access -->

</div><!-- #masthead -->
</div><!-- #header -->
<div id="main">
<div id="container">
  <div id="content" role="main">
  {%block content%}{%endblock%}
  </div><!-- #content -->
</div><!-- #container -->

<div id="primary" class="widget-area" role="complementary">
  {% load jobs_tags %}
  {% get_latest_content jobs.category 20 as latest_categories %}
{% comment %}  {% get_latest_content jobs.entry 20 as latest_entries %} 
<ul class="xoxo">
{% if latest_entries %}
<li id="recent-posts" class="widget-container widget_recent_entries">
    <h3 class="widget-title">{% trans "Recent Posts" %}</h3>
    <ul>
    {% for entry in latest_entries %}
    <li><a href="{{entry.get_absolute_url}}" title="{{entry.pub_date}}">{% trans entry.title %}</a></li>
    {% endfor %}
    </ul>
</li>
{% endif %}
{% endcomment %}
{% if latest_categories %}
<li id="categories" class="widget-container widget_categories">
    <h3 class="widget-title">{% trans "Categories" %}</h3>
    <ul>
    {% for category in latest_categories %}
    {% get_category_entries_count category %}
    {% if count > 0 %}
    <li><h3><a href="{{prefix_abs_uri}}{{category.get_absolute_url}}" title="View all posts under: {{category}}">{% trans category.title %} ({{count}})</a></h3></li>
    {% else %}
    <li><h3><a href="{{prefix_abs_uri}}{{category.get_absolute_url}}" title="View all posts under: {{category}}">{% trans category.title %} </a></h3></li>
    {% endif %}
    {% endfor %}
    </ul>
</li>
{% endif %}
</ul>
<div>
<div>
<h3><a href="http://feedburner.google.com/fb/a/mailverify?uri=pythonjobsph&amp;loc=en_US" target="_blank" title="Click to subscribe" >Subscribe to Latest Jobs for Python Jobs PH by Email</a></h3>
</div>
<br />
<div>
<div id="fb-root"></div>
<script>(function(d){
  var js, id = 'facebook-jssdk'; if (d.getElementById(id)) {return;}
  js = d.createElement('script'); js.id = id; js.async = true;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
  d.getElementsByTagName('head')[0].appendChild(js);
}(document));</script>
<div class="fb-like-box" data-href="http://www.facebook.com/pages/Python-Jobs-PH/137688669661037" data-width="220" data-show-faces="true" data-stream="false" data-header="true"></div>
</div>
  {%block primary%}{%endblock%}
</div><!-- #primary .widget-area -->

<div id="secondary" class="widget-area" role="complementary">
  {%block secondary%}{%endblock%}
</div><!-- #secondary .widget-area -->

</div><!-- #main -->

<div id="footer" role="contentinfo">
  <div id="colophon">

    <div id="site-info">
     {%block footer %}{%endblock%}
    </div><!-- #site-info -->

    <div id="site-generator">
    <!-- <p>{% trans "Copyright &copy 2011" %} {{settings.SITE_AUTHOR}} </p> -->
    <br />
    </div><!-- #site-generator -->

  </div><!-- #colophon -->
</div><!-- #footer -->
    </div><!-- #wrapper -->
  </body>
</html>

templates/faq.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "Faq" %}{% endblock%}

{% block content %}
<h3>Frequently Asked Questions</h3>
<ol>
<li>Why did you built this site? <br />Ans: Because I believe Python deserves more love and attention.</li>
<li>Is it free to post jobs? <br/>Ans: Yes absolutely free.</li>
<li>How many jobs can I post per day?<br /> Ans: Unlimited.</li>
<li>Can I post non-Python related jobs?<br /> Ans: Yes sure.</li>
<li>I already posted a Job, why it isn't showing in the list?<br />
Ans: Posted jobs will be subject for approval. It will be online soon. Be patient.</li>
<li>More to come</li>
</ol>
<p>P.S.: Please don't post spammy content, If you do that I will just happily delete your profile anyway and ban you from this site. You've been warned.</p>
{% endblock %}

{% block meta %}
<meta name="description" content="{{settings.SITE_DESCRIPTION}}" />
<meta name="keywords" content="{{settings.SITE_KEYWORDS|join:', '}}" />
{% endblock%}

templates/home.html
{% extends "base.html" %}
{% load i18n %}
{% load jobs_tags %}

{% block title %}{% trans "Home" %}{% endblock%}

{% block content %}
{% if posts %}
<ul>
{% for entry in posts %}
<li>
<strong><a href="{{prefix_abs_uri}}{{entry.get_absolute_url}}">{% trans entry.job_title|title %} </a></strong>
<div style="font-size: smaller;padding:0px;">{{entry.company_name|title}}, {{entry.location|get_location}}, posted {{entry.pub_date|timesince|split:','}} ago</div>
<div style="font-size: smaller;padding:0px;">{{entry.body_html|striptags|truncatewords:30}}</div>
</li>
<br />
{% endfor %}
</ul>
{% else %}
<h3>Sorry no posts yet. Do you want to post jobs? Try it. It's free.</h3>
{% endif %}

{% endblock %}

{% block meta %}
<meta name="description" content="{{settings.SITE_DESCRIPTION}}" />
<meta name="keywords" content="{{settings.SITE_KEYWORDS|join:', '}}" />
{% endblock%}